# docker/dockerfile
FROM python:3.12-slim

# 컨테이너 내부 기준 디렉토리 설정
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src
WORKDIR /app/src

# 실행은 docker-compose에서 command로 분기
